### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

### ISSUE THREAD

**Issue by hantrungkien** [PRNDcompany/ReadMoreTextView#4]
This is my log:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:2036)
        at .presentation.widget.ReadMoreTextView.getAdjustCutCount(ReadMoreTextView:137)
        at .presentation.widget.ReadMoreTextView.setupReadMore(ReadMoreTextView:109)
        at .presentation.widget.ReadMoreTextView.access$setupReadMore(ReadMoreTextView:18)
        at .presentation.widget.ReadMoreTextView$setText$$inlined$doOnLayout$1$lambda$1.run(ReadMoreTextView:99)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6819)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


```

**Comment by fluttergoat** [comment]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
